### ISSUE TITLE
Incorporate feature to upload/preview hydrologic region polygons

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#102]
Will discuss on call on 1/7, this should be added to the "Add Hydrologic Region" interface (was called Add Regression Region, not sure if it's updated).

We need the user to be able to upload a polygon of the hydrologic region, preview it to verify it, and submit. Eventually, this will send the polygon along to the services, but that endpoint does not exist yet. We'll also eventually want to allow the user to edit existing polygons.

Sample file to come.

**Comment by kjacobsen16** [comment]
Example shp -> [test_regA.zip](https://github.com/USGS-WiM/NSS/files/4036253/test_regA.zip)

See if there's a way to convert shp to geojson using some library in angular

**Comment by amedenblik** [comment]
I'm planning to work on this issue.

**Comment by amedenblik** [comment]
Issue complete aside from sending the polygon to services and allowing the user to edit polygons.

**Comment by kjacobsen16** [comment]
This is now completed in the NSSServices. A couple notes:
1. I enabled an parameter called "getpolygon" that allows you to get a geojson of the reg region polygon from the services: https://test.streamstats.usgs.gov/docs/nssservicesv2/#/RegressionRegions/GET/RegressionRegion (if no location is assigned, you won't get one back). This should only be used when you need it, like if the user wants to view the polygon and upload a new one.
2. You can now send through a `location` object as part of editing a regression region. So, you'd send through the regression region object, but with an added property `location` that contains a property `geometry` equal to the geojson of the polygon. See attached zip for an example of the body to send through to the edit regression region endpoint. You can run this through any rest client to test how it works (let me know if you have questions about that).
[sampleRegRegionPolygon.zip](https://github.com/USGS-WiM/NSS/files/4320529/sampleRegRegionPolygon.zip)

**Comment by amedenblik** [comment]
I have run out of hours to work on this issue. There are a number of bugs remaining. Some of these bugs are not critical and may be pushed to other issues. Please let me know if you have questions.

- [x] ~~When you try to upload a multipolygon, only one of the polygons is returned. You can test this by creating a region with this shapefile ([Albers_to_KJ.zip](https://github.com/USGS-WiM/NSS/files/4462803/Albers_to_KJ.zip)) and then editing that region in the "Edit Scenarios" mode. I'm not sure if only one polygon is getting sent to the database, or if the map is only displaying one polygon, or if there is another issue.~~ Somehow indicate to users that shapefiles must contain only one polygon.
- [x] When you click the "Edit Regression Region" icon and the modal pops up, it takes a few seconds for the form fields to populate.
- [x] When you click "Save" in the "Edit Regression Region" modal, the modal does not close. 
- [x] When you click "Save" in the "Edit Regression Region" modal, it takes a long time to update the regression region and citation. Harper (4/28/20) - Added a loader, not sure how to make faster.
- [x] When you try to edit parameters or scenarios in the "Edit Scenarios" mode, the "Edit Regression Region" modal appears instead.
- [x] Add a loader of some kind for the map in the "Edit Regression Region" while it loads the shapefile. This could also be accomplished by having a spinner icon on the "Upload File" button.
- [x] Add a citation manager in the "Edit Regression Region" modal.
- [x] When you click "Save" in the "Edit Regression Region" modal, the Regression Region info is not updated in the "Edit Scenarios" mode. For example, if you change the name of the Regression Region, the new name does not appear after the modal is closed. 
- [x] When you open the "Edit Regression Region" modal, the map is not centered on the polygon.
- [x] When you upload a new shapefile in the "Edit Regression Region" modal, the previous polygon may still show up on the map.
- [x] This branch needs to be updated to latest version of the dev branch. 
- [x] Please ensure that citations are being updated properly from the "Edit Regression Region" polygon.
- [ ] The code should generally be cleaned up to delete defunct functions. Many editing functions were removed from the Mainview component and replaced by functions in the AddRegressionRegion component.

**Comment by kjacobsen16** [comment]
Thanks Andrea! I'll look more at this, but one quick note: I think we can ignore that first issue. Ryan said we can tell users to just have one polygon in their shapefile, and that will probably be easier for them anyway.

**Comment by amedenblik** [comment]
Thanks, edited the checklist!

**Comment by kjacobsen16** [comment]
Note - the items regarding load time can use the loader once changes are brought in from dev

**Comment by kjacobsen16** [comment]
I've added an issue for "Add a citation manager in the "Edit Regression Region" modal." #162

**Comment by kjacobsen16** [comment]
@harper-wavra this is ready if you want to work on it.

Right now, the user selects a zip file to upload, then has to hit "Upload file" to put it on the map. Andrea and I discussed removing the "Upload File" button and putting the shapefile on the map when it's selected in the file upload. The reason she left it is because it has the spinner in the button. If we incorporate a different loader (like on the map as she suggested), we can remove that button.

Also - this has some big changes, so I'm guessing there will be some cleanup when we go to merge it into dev.

**Comment by kjacobsen16** [comment]
@jknewson  While working on this issue, we realized there are projection issues between the DB and what we are doing on the client. I think the shapefile-js library auto uses WGS-84 (EPSG:4326), but the DB uses Albers (ESRI:102008). I'm not familiar enough with spatial references (or services) to know the best way to handle this, or why we use what we use. I see that we can re-project a geojson in the services, because the NSS services do that through the regression regions by location endpoint.

So, as far as uploading/editing polygons in the client goes, the shapefile-js library takes any shapefile and it re-projects to EPSG:4326 to display it on the map, and the whole process of adding it to the DB and getting it from the DB to show on a map in the client works well, but when we try to get existing polygons, which are in Albers, shown in the client it doesn't work. I don't see a way of setting the projection to Albers on the client side, unless I'm missing something (which is very possible).

Would we want to re-project new polygons to Albers in the services before sending through? As in, if a polygon is sent through in the POST and PUT regression region endpoints, we would re-project it then? If so, what would be the best way to send through the polygon so it works in the client? Sorry if these are dumb questions, I just want to make sure I'm doing this the right way.

**Comment by kjacobsen16** [comment]
Never mind, I think I was overthinking this. Ignore that comment for now.

**Comment by kjacobsen16** [comment]
I think the main decision here is whether we want to re-project in a) the services or b) the client. 

After doing some research, I think our best bet is to re-project on the services side, and project the polygons to [WGS84 Web Mercator/EPSG:3857](https://spatialreference.org/ref/sr-org/epsg3857-wgs84-web-mercator-auxiliary-sphere/) before sending it to the [Get Regression Region endpoint](https://test.streamstats.usgs.gov/docs/nssservices/#/RegressionRegions/GET/RegressionRegion). After some research, WGS84 Web Mercator is actually Leaflet's default projection, and seemingly the common projection for web-based maps.

So, I'll re-project in the services to Web Mercator before sending the polygons in the regression region endpoint, and when a new polygon is sent through from the client, it'll re-project to Albers before adding to the DB.

@jknewson let me know if you disagree with this. Sorry for the 🎢

**Comment by kjacobsen16** [comment]
@harper-wavra I'm still working on getting the services to re-project, but I noticed another issue while working on this. You can't get to the settings page anymore. It appears this is due to the `ngOnDestroy` function in the mainview component, which can be removed since the modals aren't used in the mainview component anymore.

**Comment by kjacobsen16** [comment]
@harper-wavra one more note on this issue - make sure when no citation is given in the add/edit regression region modal that the `citationID` is sent through is null, not the `citation` property. I'm not sure if it's an issue, but it looks like somewhere along the way a citation got sent through as null.
