### ISSUE TITLE
Hydrograph Update Issue

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#124]
Changing the hydrograph recurrence interval and lag time works the first time scenarios are run, but when I run a different scenario, they don't update the hydrograph.

This is an important issue, let me know if you need me to show you where the hydrograph is.

**Comment by kjacobsen16** [comment]
Hold off on this until we hear back from Pete, might delete Hydrograph

**Comment by kjacobsen16** [comment]
@USGSPMM3 Have you thought more about us removing the hydrograph from the NSS client?

**Comment by HansVraga** [comment]
as per https://github.com/USGS-WiM/NSS/issues/184
