### ISSUE TITLE
Add loader to main page

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#129]
We should add a loader on the main page until the regions list is returned (and possibly other places). Sometimes I get to the app and the dropdown doesn't work because the region list hasn't loaded yet.

An example: https://test.wim.usgs.gov/liqwids/?characteristic=Nitrate,Nitrogen&minResults=1, we might be able to replicate this, or have Mitch help out.

**Comment by harper-wavra** [comment]
Throughout the app there are places that could use loaders when making services calls.
