### ISSUE TITLE
Enable assigning new Region on Clone Scenario

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#132]
Add option to change the region for a scenario when cloning, which means the regression regions will also need to update

**Comment by kjacobsen16** [comment]
Now that I made this, I can't remember if this is something Pete asked for or I thought of.

@HansVraga do you know if they want this?

**Comment by HansVraga** [comment]
I suspect so, I thought the primary reason for cloning was if you had a very similar Scenario for a new region; but we should bounce this off Ryan or Pete to be sure.

**Comment by USGSPMM3** [comment]
The case is to be able to clone a current set of regression equations and regions for updated reports or methods. Frequently the new report uses the same explanatory variables and regions and only needs to update the exponents. Under the new system going forward, we need to maintain the old equation until the new equation is "live". Thus, clone the old equations and regions, allow them to be edited, and posted as test equations.

**Comment by HansVraga** [comment]
Ryan adds:
>Yes, this is functionality that we will want. It would be useful for a few other things, too. Like say we need to edit equations to give a variable a more descriptive name. We can export the equations and swap out the old statlabel for the new one. I've also used it if a state comes online with new equations that are very similar to ones used in a different state. Rather than typing out all the equations, I can copy them in from the similar state and edit.
