### ISSUE TITLE
Get basic gagestats interface added in

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#134]
The branch used for this at this moment will probably be more like a "feature branch" (from Blake's presentation), where it's created along side dev but might not be merged for a bit.

**Comment by amedenblik** [comment]
![image](https://user-images.githubusercontent.com/40237491/76996369-c5b78080-6927-11ea-82e9-df643348fc0c.png)


Make a basic Gagestats page: a separate page, sidebar, etc.

**Comment by amedenblik** [comment]
Consider renaming NSS tab to something else...Regression Equations?

**Comment by kjacobsen16** [comment]
This should be broken out into more issues

**Comment by harper-wavra** [comment]
Added issues #136, #137, #138, #227, #228, #229, and #230 to split up this issue. This issue could probably be closed.
