### ISSUE TITLE
Add agencies and station type to lookups

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#136]
Under settings add agencies and stations type to lookups.

**Comment by kjacobsen16** [comment]
The documentation is up, so we can start adding these: https://test.streamstats.usgs.gov/docs/gagestatsservices/#/

I can't get authentication to work so I created an issue here: https://github.com/USGS-WiM/GageStatsServices/issues/7. We can still add the functions, but the post/put/delete requests just won't work yet.

**Comment by kjacobsen16** [comment]
Update - I _partially_ fixed the authentication for the gage stats services, so sending the auth header with the testAdmin token will work, other users will not yet. So, if you're logged in as the testAdmin user, the auth header will function the same as the other components.

**Comment by ltmetz** [comment]
@kjacobsen16 Hey, should I wait a bit on the issue until the framework is a bit more flushed out - with a gagestats section? I started working on the issue, but I can pause if that makes sense, and then work on something else.

**Comment by kjacobsen16** [comment]
@ltmetz no, this is fine to go ahead with, since this is in the "Settings" page, not the gagestats page. So you're basically duplicating the already existing pages here:
![image](https://user-images.githubusercontent.com/35497731/87179290-1cb0df00-c2a4-11ea-89ad-1931fe3f5fc2.png)

**Comment by kjacobsen16** [comment]
The main difference will be in the config.json, which is used to store the base urls. You'll need to add a gagestats base url there that points to `https://test.streamstats.usgs.gov/gagestatsservices/` rather than `/nssservices/`

**Comment by ltmetz** [comment]
Okay, yes. That is what I was trying to figure out... can I change the name of the other base url and have two base urls? I am still working my way around this angular app!

**Comment by kjacobsen16** [comment]
Yes, I think that's a good idea! You'll just have to do a search and replace for everywhere that's used in the project (really easy in vscode)

**Comment by ltmetz** [comment]
@kjacobsen16, I was able to figure out how to add the agencies and get them to show up (with Erik's help!), however as I am testing, I get the 401 error saying that my bearer token is invalid. I am logged into the app using the testAdmin login. Or am I missing something?

**Comment by kjacobsen16** [comment]
Hm, I just ran through post and delete using the testAdmin and it worked. Have you tried testing out the endpoints in insomnia and comparing?

Also - for now the only user that will work for this is testAdmin (just an FYI), there's some issues with users in gagestats, but testAdmin should be able to do everything

**Comment by ltmetz** [comment]
I tried the same thing in Insomnia and it says the same thing

**Comment by kjacobsen16** [comment]
Do you have an authorization header with the bearer token in Insomnia? (I mentioned this briefly on the call but might need more explanation)

**Comment by ltmetz** [comment]
Yes, I do have that in there and I am pretty sure I have it the way you had it. You copy the entire string after the authorization header, correct?
