### ISSUE TITLE
Bulk Upload

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#138]
Add button in order to do Bulk Upload of new stations. 

Might need to do research on deciding the best way to bulk upload.
- upload cvs?
- copy in table?

![thumbnail](https://user-images.githubusercontent.com/59063181/87052816-db96cd00-c1c6-11ea-855b-d8000b49b7f1.png)

**Comment by kjacobsen16** [comment]
We should actually call this "Batch upload", and sounds like the best way is to accept an excel/csv doc. We'll have to have examples of what we want it to look like. Sounds like we'll need more than just adding stations in batch, but also statistics and characteristics for those stations.

**Comment by kjacobsen16** [comment]
[example_statistics_SSDB_input_file.xlsx](https://github.com/USGS-WiM/NSS/files/4938301/example_statistics_SSDB_input_file.xlsx)
☝️ here's a starting example from Ryan. We should adapt this and make a template for users to download/fill in/upload with their gages.

**Comment by kjacobsen16** [comment]
I edited the document from Ryan to work more with how our services would work. I think in the bulk upload interface, you'll choose either to bulk upload Stations, Statistics, or Characteristics. 

Hans and I are going to look into how bulk upload was handled in the SS wateruse client and see if we can take some ideas from that.  The general idea is (1) they select the upload they want to do, (2) upload a file, then (3) the client parses it and shows it as a table that they can double-check. As I mention in the doc, they should upload based on a single citation, so we should (4) give them the ability to add a new citation, or select from the existing citations, for the whole upload (having them assign a citation to separate rows would be too difficult and things are usually published together). Also, if the codes they give for any look-ups don't work, we can (5) outline that table cell and have them select the value from the existing options using a dropdown.

(6) If they try to upload statistics/characteristics and one of the stations doesn't exist, we should force them to upload the stations, then try again.

[example_gagestats_bulk_upload.xlsx](https://github.com/USGS-WiM/NSS/files/4991049/example_gagestats_bulk_upload.xlsx)

**Comment by Anders-Hopkins** [comment]
For the batch upload, I'm assuming all stations/chars/stats will be in .xlsx files rather than .csv files. Just for doing some simple googling, I think this library might work for this task: https://github.com/SheetJS/sheetjs/tree/master/demos/typescript

**Comment by kjacobsen16** [comment]
@Anders-Hopkins making a note here: Pete wants us to see if the cell formatting in the spreadsheet gets applied when we pull the values in. If it does, he'd like us to see if it's possible to remove the formatting and pull the raw data.
