### ISSUE TITLE
Rethink "login"

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#144]
User might think they need to login for functionality, maybe change link to say "Manage" instead of "Login", or add subtext in log in modal

**Comment by harper-wavra** [comment]
Are we thinking change the text to "Manage" instead of "Login"? Or do we want the subtext?

**Comment by kjacobsen16** [comment]
Good question - I sent a message to Ryan for his opinion

**Comment by kjacobsen16** [comment]
Ryan says we should go with the "Manage" instead of "Login" route.

**Comment by kjacobsen16** [comment]
Also - maybe the heading of the login modal once it's open can say "Manager Login"?
