### ISSUE TITLE
Incorporate Freshdesk For Reporting Bugs

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#145]

**Comment by kjacobsen16** [comment]
![image](https://user-images.githubusercontent.com/35497731/77100081-06280480-69e3-11ea-83ca-17a080075f5f.png)
From SS client "Help" window

**Comment by harper-wavra** [comment]
Where do we want this located on our app? In the "about" or somewhere different?

**Comment by kjacobsen16** [comment]
Yeah I think the about would be fine for now

**Comment by kjacobsen16** [comment]
You can find it in streamstats in the "Help" modal https://streamstats.usgs.gov/ss/
