### ISSUE TITLE
Add method property to equations

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#155]
This is waiting on https://github.com/USGS-WiM/NSSServices/issues/115. We'll need an aditional "method" property for the equations/scenarios. This will mean an added property when creating a new scenario, and an added column when editing a scenario.

We'll also likely need the method types in the settings page

**Comment by harper-wavra** [comment]
Add a field for method of regression:
- Generalized least squares (GLS) 
- Weighted least square (WLS) 
- Ordinary least squares (OLS)


Based on method of regression the field that is currently labeled the field name for variance should change:
- For GLS: "Model error variance”   ![image](https://user-images.githubusercontent.com/59063181/81211961-c53b7d80-8f99-11ea-84d3-ce25572f92b2.png)

- For OLS/WLS: “Model mean square error” MSE, in log units

**Comment by kjacobsen16** [comment]
This is now implemented in the services via the `/methods/` endpoint. A `methodID` is attached to the regression regions, rather than the equations. So the method should be an option when creating a regression region, displayed somehow for that regression region, and will eventually be used to determine prediction intervals (this is slated for next fiscal year).

Because there are limited options, I only made the `get` functions available, so there are no add/edit/delete endpoints for this resource.

**Comment by harper-wavra** [comment]
I was just looking at a couple of the regression regions in the services and was unable to find any with a methodID attached. Could you provide a regression region that has a methodID? 
and just to clarify, for now/this issue we only want to display the method id for the regression regions?

**Comment by kjacobsen16** [comment]
@harper-wavra I missed the second part of your question. We should display the code or name instead of the id - I'd go with code for now, I'm expecting the user will know what it stands for

**Comment by harper-wavra** [comment]
Is have a method required for creating a new regression region or optional? Also should the methods be added to the settings page? Do you want to be able to edit/add/delete them?

**Comment by kjacobsen16** [comment]
@USGSPMM3 see Harper's question above

**Comment by USGSPMM3** [comment]
@harper-wavra 
I would say that it should be required. We may need an "NA" field if it is not applicable and I think KJ and I talked about creating one? We will discuss where methods will be and edit/add/delete functionality

**Comment by harper-wavra** [comment]
Methods should be required for each regression region, use undefined if not applicable. We should also be able to edit/add/delete methods in the settings page (for now I will just display them until [service issue #175 ](https://github.com/USGS-WiM/NSSServices/issues/175) is done.) Still need to figure out the best way to go through and assign methods to the existing regression regions as of now none of the regression regions (besides test) have a method assigned.
