### ISSUE TITLE
Example/Explanations

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#166]
Add examples or a link to a help document for the following inputs
- [ ] Equation, When adding a new scenario have an example equation
- [ ] Parameter Min and Parameter Max, should have a short explanation indicating minimum and maximum values used in regression equation development 
- [ ] XI Row Vector, When adding a new scenario have an example for how to enter XI row vector
- [ ] Covariance Matrix, When adding a new scenario have an example for how to enter covariance matrix
- [ ] See image below, When adding a new scenario the below section needs a header/explanation (maybe "Equation Test")
![image](https://user-images.githubusercontent.com/59063181/79769486-cad66980-82f1-11ea-8e84-a1492ff17450.png)

From Pete's Feedback 4/16/20

**Comment by harper-wavra** [comment]
@kjacobsen16 @USGSPMM3

**Comment by kjacobsen16** [comment]
@harper-wavra I can speak to a few of these, but I'll let @USGSPMM3 have the final word here.
1. Any existing equation (one that we didn't add in testing) should be fine. Something like `42.2*(DRNAREA)^(0.863)*(LAKEAREA+1)^(-0.54)`. I got this from MN Region C 1.5 Year Peak Flood.
2. You can make this like the little information circles in the sidebar (image below).
![image](https://user-images.githubusercontent.com/35497731/84040173-ea8c2480-a967-11ea-9758-69d65d19dd1f.png)
3. I'll let Pete speak to this one (I'm not very familiar with this part). If you want to keep consistent with the example equation, the xi row vector for that is `["logN(DRNAREA,10)","logN((1+LAKEAREA),10)"]`
4. This will change when we finish #167, but again I'll let Pete speak to this one. For the example equation, the covariance matrix is `[["0.0038028","-0.001987","0.00076235"],["-0.001987","0.0032803","-0.0058925"],["0.00076235","-0.0058925","0.023215"]]`
5. I think this is self explanatory.

**Comment by USGSPMM3** [comment]
@kjacobsen16 is correct on all of these. Thank you KJ!
