### ISSUE TITLE
Change “Regression Type” to “Independent Variable”

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#181]
When creating a new scenario change the label “Regression Type” to “Independent Variable.”

From Pete's Feedback 4/16/20

**Comment by kjacobsen16** [comment]
@NathanKrawza right after I merged your pull request, I realized this is probably not what Pete meant. I discussed it with him, and we should actually change this to "Regression Variable". Sorry for the confusion 😅

**Comment by NathanKrawza** [comment]
Haha all good! Does it look okay now? I just updated that line to say "Regression Variable"

**Comment by kjacobsen16** [comment]
Yep that looks good! Go ahead and make a pull request
