### ISSUE TITLE
Loader screen never closes when clicking "Compute"

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#191]
If you click "Compute" on the sidebar and have left one or more values  blank the loader screen never closes.
![image](https://user-images.githubusercontent.com/59063181/81825307-1ac4dc80-94fc-11ea-8f55-94aadfc08ac8.png)

From Pete's feedback 5/13/2020

**Comment by kjacobsen16** [comment]
Looking at Pete's images, he hit compute directly from "Edit Scenarios". I think if that's the case, we should do some checks to make sure they're not editing anything, then if the parameters aren't filled in, we should take them back to the parameter inputs.

I also think having a user guide will help a lot. I think he was trying to finish editing but used the wrong button.

Edit: we could also disable the "Compute" button until they click "finish editing"
