### ISSUE TITLE
Issues with Manage Citation modal when logged in as Manager

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#218]
When logged in as Manager the Manage Citation Modal has some issues. It seems if you are logged in as a Manager and you subscribe to the service the response doesn't include regressionRegions like it does when you are logged in as an admin.

As Admin:
![image](https://user-images.githubusercontent.com/59063181/84696514-3dd71780-af12-11ea-9991-2afe1c2e05c3.png)

As Manager:
![image](https://user-images.githubusercontent.com/59063181/84696552-4f202400-af12-11ea-86a2-f80b761d9cfa.png)

**Comment by harper-wavra** [comment]
Temporary fix in pull request #217 which removes auth header and displays all citations in Manage Citation Modal. Do we want all citation displayed or only those related to the regions the manager has access to?

**Comment by kjacobsen16** [comment]
I think we should show all citations. There are some citations that are used in multiple regions, so users might want to use citations that are used in other regions that they don't manage.

**Comment by harper-wavra** [comment]
- [x]  Disable the edit button next to citations not in their regions 
- [ ]  Disable the edit button next to regressions not in their regions ( Moved to Issue #197 )
