### ISSUE TITLE
Add sidebar to Gagstats page

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#228]
Add in a sidebar similar to the one for the regression regions for the Gagestats page. The user should be able to choose a region, then limit by station type and agency. 

![mock-up](https://user-images.githubusercontent.com/59063181/87050201-8f965900-c1c3-11ea-83a8-7a4744ac4e54.png)

**Comment by kjacobsen16** [comment]
Here's the service documentation for the stations request: https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations. We actually don't have the region as a filter option yet, but the station type and agency filters are available. There's also pagination in the query, so we should maybe have a page number shown, and allow the user to go to a certain page.

Also - we can also add the reg type, statistic group and variable type filters that are listed in the service documentation

**Comment by kjacobsen16** [comment]
Also - we should load stations right away with the default setup (no filters), with the option to filter further by the items in the sidebar.

**Comment by kjacobsen16** [comment]
Basic sidebar in with a couple filters
