### ISSUE TITLE
Display table from user input from the sidebar

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#229]
From the users input on the sidebar a table should be displayed in the mainview with each of the stations that match the users input. On the table the Type, Agency, Code, Name, Latitude, Longitude, and if it is Regulated or not should be displayed. 

![thumbnail](https://user-images.githubusercontent.com/59063181/87050577-0fbcbe80-c1c4-11ea-9a0b-6f8d74b57291.png)

**Comment by kjacobsen16** [comment]
@USGSPMM3 We have the `IsRegulated` option in GageStatsDB, but looks like it's all null. Does SSDB have this option somewhere that I can pull in? If not, should the default be "false"?
