### ISSUE TITLE
Add Station button

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#230]
In the mainview there should be a button that allows users to add a station. There could a modal that pops up when the button is clicked that allows users to enter the information for the new station. 

![thumbnail](https://user-images.githubusercontent.com/59063181/87050961-94a7d800-c1c4-11ea-970c-a454c8b64018.png)

**Comment by harper-wavra** [comment]
@kjacobsen16 might have more information for what needs to be inside the modal (Station Name, Location, Code ect) in order for a new station to be added

**Comment by kjacobsen16** [comment]
The station object generally looks like this: 
```
{
        "code":"11111111",
        "agencyID": 1,
        "name":"example station 1 at example location, ex. river",
        "stationTypeID":"1",
        "location": {
            "type": "Point",
            "coordinates": [
                "0": -99.999,
                "1": 44.444
            ]
        }
    }
```

You can explore the documentation for the stations endpoints: https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations. The SRID used for these are WGS84/ESRI WKID 4326.

**Comment by kjacobsen16** [comment]
@esmyers I missed the "isRegulated" boolean property - that will be a necessary option when creating a station.

**Comment by kjacobsen16** [comment]
Noting here - the stations now have a "regionID" property, so a region should be selected when creating a new station
