### ISSUE TITLE
css on multiselect when certain number are added

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#24]
Regression group filter list writes-over the right pane making it difficult to read.  Truncate the display of the LIMIT BY REGRESSION GROUP(S) because the chosen groups are clearly displayed in the right pane.

**Comment by troddick** [comment]
![image](https://cloud.githubusercontent.com/assets/1580076/23525239/5ff76756-ff53-11e6-86ec-5ec2b18c6632.png)

**Comment by HansVraga** [comment]
Looks good enough.
