### ISSUE TITLE
Duplicate the manager add/edit calls to also update the gagestats user endpoint

### ISSUE THREAD

**Issue by ltmetz** [USGS-WiM/NSS#240]
There's a disconnect between the users in NSS v. GageStats DBs. If someone creates a new user or tries to login with a user that's in NSS but not gagestats, it won't work. 

Issue may be resolved when https://github.com/USGS-WiM/GageStatsServices/issues/7 is completed.

**Comment by kjacobsen16** [comment]
Closing, was fixed in the services
