### ISSUE TITLE
Manage Citations Modal - Edits are sticking

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#252]
I started an edit and then cancelled, but it kept the changed url until I closed out and reopened the modal (should just be `/nss/`, the `/nss-dev/` wasn't actually saved).
![image](https://user-images.githubusercontent.com/35497731/88831094-7b2af800-d194-11ea-99a9-04d244cf7514.png)

**Comment by kjacobsen16** [comment]
Oh, I just noticed, when I reopened the modal, it had the old one and the new one when I re-filtered. Only refreshing the page cleared the non-saved edit.

**Comment by harper-wavra** [comment]
Completed this issue in pull request #258
