### ISSUE TITLE
Styling fixes

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#253]
- [x]  Variables dropdown errors feel a little smushed in add scenario modal (to replicate - go to add scenario modal and hit the "Add Parameter" button
![image](https://user-images.githubusercontent.com/35497731/88830067-102cf180-d193-11ea-9421-3565b7096c7e.png)

- [x] Manage citations modal column headers are off 
![image](https://user-images.githubusercontent.com/35497731/88830906-3a32e380-d194-11ea-984f-1c46955fc7f2.png)

**Comment by kjacobsen16** [comment]
@harper-wavra if you notice any small styling issues, you can add them here

**Comment by harper-wavra** [comment]
- [x] When not logged in the icons on the sidebar are spaced differently
[image](https://user-images.githubusercontent.com/59063181/88832156-048efa00-d196-11ea-8d8e-fa18f38650ef.png)
- [x] In settings the New Regression Type and New Station Type modals are missing the new button classes
[New Regression Type](https://user-images.githubusercontent.com/59063181/88832865-0c02d300-d197-11ea-920e-4942b0c9e738.png)
[New Station Type](https://user-images.githubusercontent.com/59063181/88832909-1b821c00-d197-11ea-8306-6c00d568e9c1.png)

**Comment by kjacobsen16** [comment]
New issue: the equations section (shown after computing scenarios on the main page) runs together. Before, each equation was on a separate line
![image](https://user-images.githubusercontent.com/35497731/89039470-c1ed2f00-d307-11ea-85b5-e87894c00380.png)
