### ISSUE TITLE
logic of LIMIT filters vs FILTER limits

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#26]
It is confusing that having all items checked in one of the LIMIT filters is the same effect as having no items checked.  It would be better if having no items checked actually meant no items, and then maybe have it default to all items checked when you first enter the filter.

**Comment by troddick** [comment]
Would it make more sense if it said "FILTER BY ..." rather than "LIMIT BY ..."?
Having nothing selected is saying I do not want to filter by anything, just show me all. If you select one or more, than it is saying I want to now see the results with these selected things only. Selecting one or more is adding those to the query in the services. Not having any selected is therefore not limiting the results coming back by anything in that list. 
Does that make sense?

**Comment by tkoenigusgs** [comment]
I understand where you are coming from and agree with your logic.  My perspective is shaped mostly by Excel and Google Sheets, where an unfiltered column shows all items checked by default when you first visit the filter.  If I want to filter a column in one of those two products by one or tow items, then I have to first uncheck all before I can check the 1 or 2 that I want.  You're actually saving me some clicks by starting them all unchecked, and that's fine.  No big deal, but I was just shooting for consistency with other applications.

**Comment by tkoenigusgs** [comment]
Oops.  Accidentally closed this one.  Re-opening...
