### ISSUE TITLE
Selecting item per page

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#267]
Have an option for the user to select the number of stations that are shown per page in the gage stats table. Maybe something like: 
 
![image](https://user-images.githubusercontent.com/59063181/90269804-d7da1400-de1e-11ea-836f-63dab888ab13.png)

The page count is an optional parameters. Default page count is 50, but we can adjust that using the pageCount query parameter. https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations

**Comment by harper-wavra** [comment]
What should the options be for the drop down (maybe 15, 25, 50, 100)? or do we want the user to be able to enter their own page count?

**Comment by kjacobsen16** [comment]
I think those options sound good to me (and we can always adjust).
