### ISSUE TITLE
% area weight input boxes

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#27]
"% Area Weight input boxes should only show when there is a single" -- Todd

**Comment by troddick** [comment]
My understanding what the we allow them to add % Area Weight when more than one regression group is chosen, and the % area weight needs to be populated and add up to 100.
Did I misunderstand the use of % Area Weight?

**Comment by jknewson** [comment]
You are correct Tonia, When a user selects a statistic group (peakflows for example) and selects 2 regions, they should provide an % of each area the study resides.

**Comment by jknewson** [comment]
FYI, if the % doesn't add up to 100 or exceeds 100, the services will not apply an area weight and supply a warning msg. 
Just letting you know, so you don't necessarily need to validate the sum to 100,

**Comment by tkoenigusgs** [comment]
I have no idea what I was thinking when i wrote that one.  Please close/ignore.

**Comment by tkoenigusgs** [comment]
Ooops.  I accidentally closed this one before I understood the behavior of the buttons.  But this one can probably stay closed.
