### ISSUE TITLE
Make gagepage editable

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#275]
Gagepage should be editable. There should be buttons to add a new char/stat as well as buttons (maybe like when you edit a regression) to edit a char/stat.
 
![image](https://user-images.githubusercontent.com/59063181/91064689-33fa2080-e5f5-11ea-9b16-b9b316e61844.png)

**Comment by Anders-Hopkins** [comment]
Question about adding characteristics and statistics: when we click the 'add characteristic' button, do we want a new empty row to be added to the table? Or should another form pop-up with inputs for characteristic parameters. The Gage info is already displayed in a form, so is it even possible to have another form pop-up?

![edittable](https://user-images.githubusercontent.com/55411265/92132356-abd20300-edcc-11ea-903e-51506c324b0d.PNG)

**Comment by kjacobsen16** [comment]
It is possible to have another window on top, but I like your idea to add an empty row.
