### ISSUE TITLE
Filter regression variables bases on selected  statistic group

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#277]
When the statistic group has been selected the regression variables should be filtered to that group (i.e. when Peak-Flow Statistics is selected only peak flow variables should be displayed in the regression variable. 

We have a filter for the endpoint, https://test.streamstats.usgs.gov/nssservices/regressiontypes?statisticgroups=2

We should try to build in an option to remove the filter as well.

**Comment by harper-wavra** [comment]
Do we want this filtered only when we are creating a new scenario? The sidebar filters already so I don't think we would want it there. I think new scenario would be the only spot but is there any other place where this would need this to be filtered?

**Comment by kjacobsen16** [comment]
I think the request from Pete was targeted toward the add scenario modal. It might be useful to add it in the settings page for the regression variables, though.

**Comment by kjacobsen16** [comment]
@USGSPMM3 our language for these are inconsistent. I think we use regression type or statistic mainly throughout the app. Is there a better term for users, such as "Regression Variables"? The DB/services just calls them regression types.
