### ISSUE TITLE
Change "Parameter" and "Variable" labels to "Explanatory Variable"

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#278]
In the add scenario modal "Add parameter" brings up a "variable" box. The names on these (ie "parameter" and "variable") should both be changed to "explanatory variable." Also the "Parameter" label in the Edit scenario in mainview. 

![image](https://user-images.githubusercontent.com/59063181/91194351-ae8e7300-e6bd-11ea-93d0-5d614d193a9b.png)
![image](https://user-images.githubusercontent.com/59063181/91194462-c9f97e00-e6bd-11ea-966c-de8a0dd848da.png)

**Comment by kjacobsen16** [comment]
It's also called "Parameter" on the main computation page 
![image](https://user-images.githubusercontent.com/35497731/91195411-966b2380-e6be-11ea-9991-d7a5f0f42c58.png)
