### ISSUE TITLE
Add region filter to stations

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#286]
The stations call now has a regions filter enabled, see the [service documentation](https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations) for more info.

**Comment by kjacobsen16** [comment]
@harper-wavra when you do this, can you look into the other filters available for this endpoint in the service documentation? It looks like there are some more filters I set up for the stations query, but I don't remember setting them up so we'll want to test those. If they're working we should add them into the client as well

**Comment by harper-wavra** [comment]
Similar question to the one I asked on the pull request. Should I be using the gagestats services or should I use the nssservices to get the regions, regressionTypes, variableTypes and statisticGroups?

**Comment by kjacobsen16** [comment]
Same answer - they use the same tables, but to be consistent we should use the gagestatsservices in the gagestats portion
