### ISSUE TITLE
Gage Page Modal changes

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#296]
This is something we'll want to communicate with Marty since we want the gage page to look the same on the client. 

1. display the statistic group name
2. allow user to filter which statistics they want shown by the statistic group
3. allow user to select "show all reported statistics" or "show all preferred statistics" (hide anything with IsPreferred = false)

**Note**: this is the modal that displays when you click on a gage in the gagestats table.

**Comment by Anders-Hopkins** [comment]
For 1 and 2, I think this could be achieved with a dropdown menu which contains the stat groups. This could be used to display the Stat Group name and to filter the stat table below it. Then for 3, a button or drop down above the stat table could be used to filter preferred/not preferred stats. How does this sound?

![GPModal](https://user-images.githubusercontent.com/55411265/93782381-1fa74480-fbf0-11ea-9fbf-e2440d3fe1c3.PNG)

**Comment by kjacobsen16** [comment]
Good idea! the only thing I'm thinking is for displaying the statistic group, I think adding a small line in the table would be helpful. For example, see how the statistic group labels (Flow Duration Statistics, etc.) are in an old gage page here: https://streamstatsags.cr.usgs.gov/gagepages/html/05059300.htm.

**Comment by kjacobsen16** [comment]
@harper-wavra @Anders-Hopkins not sure who's working on this, but we want to change the "Legacy NWIS Link" to point to the new NWIS link: https://waterdata.usgs.gov/monitoring-location/06680500/

Edit: Clarifying: the actual URL you'll use is "https://waterdata.usgs.gov/monitoring-location/" + gage.code

**Comment by kjacobsen16** [comment]
If this is still in progress - we want the citations link to open the citationURL in a new tab

Also - I realized that we are pointing to the new NWIS link (as well as the legacy NWIS link), so that last comment of mine can be disregarded. We do want to add a `target="_blank"` to make sure it opens in a new tab though

**Comment by Anders-Hopkins** [comment]
Yea, this is still in progress. I'll be sure to include the set the citation link to open in a new tab.
