### ISSUE TITLE
extra line return

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#33]
Remove the line between the first two title lines.

**Comment by troddick** [comment]
I am not sure where you are referring to.
![image](https://cloud.githubusercontent.com/assets/1580076/23527018/dc3c9ac4-ff59-11e6-8ce9-7f03d1cb2e0c.png)

**Comment by tkoenigusgs** [comment]
Sorry for not being more specific.  Here it is:
![image](https://cloud.githubusercontent.com/assets/25535974/23562734/278a5e38-001a-11e7-90f3-5d2f340d104b.png)
I'm not sure why the old interface had it divided up, but it really makes the output confusing in some cases.

**Comment by troddick** [comment]
@mitch-wim , is there a css way we can do this? I have a <thead> with 2 <tr> in there for the header stuff, but I don't want the border between them.

**Comment by troddick** [comment]
fixed.
