### ISSUE TITLE
Add scenario modal changes - Expected values

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#334]
Edit: see my comment below (we still might want to consider what I wrote out here but I think the skipCheck option will be the easiest to enact).

Writing out my thoughts here, but might need more thought.

Pete and Ryan have requested to remove the "Expected" portion of the equations and instead have some sort of equation test because users won't always have example values. 

We could change the services, but I had a thought that might work for just the client: we could maybe just use the max/min of each parameter and plug it into the equation client side to send as the expected value. In this case, we could just auto-fill in the example values based on that, then it gives the user flexibility if they _do_ have example values, and if for some reason the services calculated differently than the client, the user can then adjust the expected value themselves.

**Comment by kjacobsen16** [comment]
I decided to look into the services and found a pretty easy way to do this.

Now, you can add "skipCheck=true" to the url to skip the equation values comparison. It does still check to make sure the equation is a valid equation though.

Edit: this still needs to be merged and put at the main services url, but is currently available at https://test.streamstats.usgs.gov/nssservicesv2 until then.

**Comment by kjacobsen16** [comment]
The skipCheck option is now available on https://test.streamstats.usgs.gov/nssservices. This is a good next issue if someone needs one.

**Comment by harper-wavra** [comment]
If I am understanding correctly we need to remove the expected value sections in two places: when adding a new scenario and editing a scenario? Do we want to fully remove these sections or comment them out for now?
[Edit Scenario](https://user-images.githubusercontent.com/59063181/97895256-2948bf80-1cf9-11eb-83d9-ff0183c867d9.png)
[New Scenario](https://user-images.githubusercontent.com/59063181/97895307-3cf42600-1cf9-11eb-93b2-51692ff00f17.png)

**Comment by kjacobsen16** [comment]
Hm, I think we can leave them in but add in a checkbox to "Skip Equation Calculation Check" or something like that that makes the expected/example values optional/disables them

Edit: I think disabling them (giving them the disabled class, which greys them out) would make it smoother for the user
