### ISSUE TITLE
Second citation in 'Manage Citations' is empty

### ISSUE THREAD

**Issue by ghost** [USGS-WiM/NSS#343]
Every region I've tried has a blank second citation:
![image](https://user-images.githubusercontent.com/46943254/96632996-218f2100-12de-11eb-8214-10c1b7ff15e3.png)
Steps to reproduce:
1. Click 'Manage' and login
2. Click NSS
3. Select Georgia as your region
4. Click 'Manage Citations'
5. Notice missing second citation
This citation should be removed, unless it corresponds with a real source, in which case it should be edited to include the citation information.

**Comment by Anders-Hopkins** [comment]
The citation with the id of "1" has null values for author, etc. Here is the url: https://test.streamstats.usgs.gov/gagestatsservices/citations/1

If this isn't being used for testing purposes, it could easily be deleted.

**Comment by kjacobsen16** [comment]
I'll check to see if this is stemming from SSDB (which we import into NSSDB with new releases), and if there's text that should be there.

**Comment by kjacobsen16** [comment]
It looks like the citationID is blank in SSDB, so it must be doing something weird with the import where it makes a blank citation.

We can remove that citation from the National region and delete the citation :)

**Comment by harper-wavra** [comment]
Removed citation from the National region and deleted the citation.
