### ISSUE TITLE
Changes to edit scenario

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#348]
I think the way we edit regression equations should be adapted to make the full scenario editable in one go.

Since we're already cloning the scenarios, I think we can do a similar thing where we send through the scenario to edit to the add scenario modal and instead of cloning, we let them edit and save when done.

**Comment by harper-wavra** [comment]
Been working on this a bit and I am wondering how we want to deal with editing the Explanatory Variables. Before we were editing the Explanatory Variables and the Regressions separately from their rows. Now with this issue we are able to edit both in the modal. I am not sure if we want to be able to edit the Explanatory Variables from the rows and not in the modal, or edit it all from only the modal? Or maybe there is a different way I am not seeing.

**Comment by kjacobsen16** [comment]
I'm thinking it'd probably be easiest to just carry it all to the modal. That way, we have everything we need already set up in the modal, so we don't need to remove any of that, just adapt it slightly for editing.
