### ISSUE TITLE
results response coming back in different sort order than chosen

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#36]
I noticed that results aren't always sorted the same way if weighting multiple regions.  Example: Select Idaho...Low-Flow...Region_1 and Region_2.  Enter values and notice that the three lists (Reg1, Reg2, and Avg) are sorted differently.

**Comment by troddick** [comment]
@jknewson 
Is there something we can do about this in the services before returning the response? Always sorting the results based on a property or something? Or is this something I can sort before showing (using what property?)?
![image](https://cloud.githubusercontent.com/assets/1580076/23557261/1cc34c3c-fff5-11e6-81f9-e6b5b117d56f.png)

**Comment by jknewson** [comment]
currently I think its just sorted by how id, but I think we could add a sort order in the regressiontype table, that could fix this... I've add this to nssservices  https://github.com/USGS-WiM/NSSServices/issues/49
