### ISSUE TITLE
Set timer on GagePage Toastr pop-ups

### ISSUE THREAD

**Issue by Anders-Hopkins** [USGS-WiM/NSS#360]
Toastr pop-ups are produced when new characteristics and statistics are added to a station gage. These pop-ups only disappear when the user clicks on them. This would be better if they disappear on a users' click or after 3-5 seconds.

**Comment by Anders-Hopkins** [comment]
Ok, this is waaaaaaay simpler than I thought it would be. Probably didn't need its own issue, but then I thought there would be more changes required to do this.

**Comment by kjacobsen16** [comment]
@Anders-Hopkins did this get pushed through with that last pull request?

**Comment by Anders-Hopkins** [comment]
@kjacobsen16  Yes!

**Comment by kjacobsen16** [comment]
Thanks! I just tested it and noticed that there are a few more places where a `ToasterConfig` is made that need it, should be an easy fix if someone wants to throw it in with another pull request
