### ISSUE TITLE
Updates from NSS Service Changes

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#364]
I'm including all of these here because there are some commonalities, we may want to break them out a bit further.

The variable type's defaultUnitTypeID changed to two fields: metricUnitTypeID and englishUnitTypeID

- [x] display this change in the settings page table

- [x] allow user to select both when adding/editing a variable type

- [x] In the add scenario modal, Ryan wants the users limited to selecting either the metric or english unit type when selecting the unit type for each scenario parameter - note that sometimes the english and metric will be the same (i.e. dimensionless)

Also, now the variable types have statistic groups associated with them.

- [x] Display the statistic group for each variable type in the settings page

- [x] allow the selection of a statistic group when adding/editing a variable type - note that statistic groups now have a "def type" (this was a term from SSDB to define if it's used for statistics or basin characteristics), they should only be allowed to choose stat groups with the "BC" def type

Related changes:

- [x] We should limit the statistic group selection in the add scenario modal to statistic groups with the "FS" def type

- [x] Gage Page - display the statistic groups for the basin characteristics, like we do with the statistics. Note that in this case, the statistic group is assigned to the variable type, not the characteristic like how the statistic is done.

**Comment by harper-wavra** [comment]
"In the add scenario modal, Ryan wants the users limited to selecting either the metric or english unit type when selecting the unit type for each scenario parameter - note that sometimes the english and metric will be the same (i.e. dimensionless)" 

Can the users choose between English or Metric (with like a dropdown), should they just be given English, or should they just be given Metric?

**Comment by kjacobsen16** [comment]
I think the dropdown would be limited to the two units assigned to the selected variable type, so if the english unit is miles and the metric unit is kilometers, the dropdown would only show miles or kilometers.

**Comment by harper-wavra** [comment]
"Gage Page - display the statistic groups for the basin characteristics, like we do with the statistics." If I am understanding correctly we want a new column for statistic groups displayed in the Physical Characteristics table?
![image](https://user-images.githubusercontent.com/59063181/101823330-34f58600-3af0-11eb-83e9-88058d468c06.png)

**Comment by kjacobsen16** [comment]
I think this would actually be like the "Flow-Duration Statistics" header below in that image - so it'd be more like a subheader in the table to group the characteristics.
