### ISSUE TITLE
Gagestats Lat Long

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#370]
We need to have NWIS lat/long and StreamStats lat/long.
NWIS lat/long would come from NWIS and StreamStats lat/long would be defined as gage locations snapped to the flow accumulation grid that is submitted by WSCs. This recently came up in a discussion with a WSC and they are not able to change the NWIS location, but want the gage plotted on the flow accumulation grid. Thus we need a lat/long for both. 

From Pete's Feedback 10/29/20

**Comment by kjacobsen16** [comment]
@USGSPMM3 is this something we just want for display purposes in the gage page? As in, could we pull the NWIS location in from an API, like the NLDI link? https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-07099233/?f=json

**Comment by USGSPMM3** [comment]
@kjacobsen16 I think we want to display the gages using the "StreamStats" lat/long unless it is blank, then use NWIS locations. The gage information pages should probably include both locations because in some cases they may be further apart than we would like.

**Comment by kjacobsen16** [comment]
In SS, I'm making an HTTP request to https://waterservices.usgs.gov/nwis/site?site=05047970 (using the station code). To get the lat/long, I'm using the following in AngularJS; it will likely need some changes for Angular/Typescript:
```
var regex = /[+-]?((\d+(\.\d*)?)|(\.\d+))/g;
var latLong = response.data.split(this.gage.name)[1].match(regex);
this.NWISlat = latLong[0];
this.NWISlng = latLong[1];
```

Then I'm displaying the "NWIS Latitude" and "NWIS Longitude" in the gage page using this.NWISlat and this.NWISlng
