### ISSUE TITLE
chart title move

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#38]
Put chart title at top of chart instead of below X-axis title, or make it a bolder, larger font if it can't be moved to the top.

**Comment by troddick** [comment]
The chart doesn't have a title. That tile under the x-axis is considered the x-axis title. I duplicated the way the nss.exe has the charts. 

![image](https://cloud.githubusercontent.com/assets/1580076/23528906/142e812a-ff61-11e6-9368-1c2b6caa042a.png)

I have a lot of logic in place on updating that x-axis title based on user input (in 'More Options') as well as if they change the Lag Time (hrs) value. It would require a bit of time to pull that apart and move it to a different chart property. 

I can easily make the x-axis title bold via a property the charting library has. That would make it look like:
![image](https://cloud.githubusercontent.com/assets/1580076/23529301/b6217b76-ff62-11e6-95d7-cb8b438439a7.png)

Thoughts?

**Comment by tkoenigusgs** [comment]
Making the chart title a separate chart property would be ideal.  That would allow us to bold the chart title (even if we leave it in its current place), and then we can give the x-axis title a consistent font/style with the y-axis title.

If we can't make them separate properties, then we'll just have to leave it as-is and let the publications folks sort out the elements when these are used in reports. etc.
