### ISSUE TITLE
remove chart point legend

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#39]
Remove blue dot explanation from bottom of chart.  Explanation not needed if only one thing is being plotted.

**Comment by troddick** [comment]
The blue dot can either be 1 single chart value or I was using that to communicate that the line is representing an Area Averaged by multiple Regression Groups. 
How would you like this to be communicated if I remove the blue dot explanation?

![image](https://cloud.githubusercontent.com/assets/1580076/23529812/a95f776a-ff64-11e6-9954-8850e4de3c7b.png)

**Comment by tkoenigusgs** [comment]
I see what you mean.  It does add information if the chart happens to be an area-weighted average.  So let's do this:  If it is a PK25 statistic, then let's call it "PK25", rather than "Chart".  And if it is an area-weighted PK25 statistic, then let's call it "PK25 (Area-weighted average)"

**Comment by troddick** [comment]
Done.
