### ISSUE TITLE
consistent dropdowns (all with down arrows)

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#40]
For GUI consistency, the chart drop-downs on the right side need to have down arrows just like the drop-downs in the upper left LIMITing fields.

**Comment by troddick** [comment]
Added 'select-wim' style to selects. This adds the consistent down arrow to the select.
But if the screen width is reduced, the down arrow pops out of the select and appears below it. 
Hopefully responsive design fixes by Mitch will fix this.
![image](https://cloud.githubusercontent.com/assets/1580076/23554276/01c33d76-ffea-11e6-9d2d-86bc1a2aacb0.png)

**Comment by HansVraga** [comment]
Fixed
