### ISSUE TITLE
Regression Regions with Review Status

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#415]
Regression Regions with their status set as review should not show up in the NSS read only client. 

"We have new equations in US_National study area for stream channel properties. In the NSS manage client they show up with a review status, which means they should not show up in the NSS read only client. Either we have a bad filter or the NSS read only is pointing at a different DB than the manage DB. In similar fashion we are showing the CT 2020-5054 equations and those shouldn’t be showing. "

From Pete's Review 2/2/2021

**Comment by kjacobsen16** [comment]
@harper-wavra I commented back in the review doc, but this will be fixed when we put NSS on prod. The test services (used on the test.streamstats.usgs.gov domain) show the "Review" status, but the production services will not.
