### ISSUE TITLE
Limit by regulation status

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#417]
In the GageStats sidebar we should add  “Limit by regulation status.”

From Pete's Review 

Waiting on issue - https://github.com/USGS-WiM/GageStatsServices/issues/94

**Comment by harper-wavra** [comment]
This would need some service work before we could incorporate it into the client, correct?

**Comment by kjacobsen16** [comment]
Yes, we'll need a filter added to the stations endpoint in the GageStatsServices
