### ISSUE TITLE
Rework Freshdesk connection

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSS#447]
We had a token in our repository (hard-coded) for Freshdesk.

- [x] Remove token from code active branches
- [x] create a secrets file and deployment process for handling of freshdesk token
- [ ] run cleanup script to remove token from git history

**Comment by HansVraga** [comment]
Similar activities being worked on here https://github.com/USGS-WiM/StreamStats/issues/1088

**Comment by kjacobsen16** [comment]
The secrets.json is stored in the streamstats sharepoint. We should add the following text to the "installing" section of the read me, like we did for [streamstats](https://github.com/USGS-WiM/StreamStats#installing):
>For Freshdesk functionality (used for the Help tab in the About modal), you will need the secrets.json from [here](https://doimspp.sharepoint.com/sites/StreamStatsTeam/Shared%20Documents/Forms/AllItems.aspx?viewid=9f283fd0%2D4904%2D450b%2D80ce%2Da5211e70406e&id=%2Fsites%2FStreamStatsTeam%2FShared%20Documents%2FSS%5FTeamSpace%2FV4%20Freshdesk%20Creds). This requires access to the StreamStats Sharepoint, and should be placed locally at src/data.

>Note: the secrets file is in the .gitignore and should _never_ be uploaded to GitHub
