### ISSUE TITLE
Fix Hydrograph Calculation Method

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/NSS#45]
**Update** See comments, need to use a different hydrograph calculation method.

The hydrograph chart is not plotting the same as NSS.exe plots it.  I tried Idaho...Peak...Region3 and got a different hydrograph than the one that NSS plots (e.g. at X=0.5, NSS.exe give Y=263 but NSSweb gives Y=238) for PK1_5 with lag=1.

**Comment by troddick** [comment]
@jknewson , I recall you mentioning something about this. That the data in NSS.exe (which comes from an access db) has an older version than the data in the db used for the services?

**Comment by jknewson** [comment]
nss uses the SSdb from 2017-01-13, which I think is equivalent to nssdb 2017-01-16 located https://water.usgs.gov/osw/programs/nss/history.html

**Comment by tkoenigusgs** [comment]
I don't think the data has changed for Idaho since 2009.  So this isn't likely a database version issue.  I think there is something else going on here.

**Comment by jknewson** [comment]
ok, I'm looking into this a bit more, just a sec

**Comment by jknewson** [comment]
OK, maybe the computations are different on how the Hydrographs are computed. The method currently used comes from TECHNIQUES FOR ESTIMATING FLOOD HYDROGRAPHS FOR UNGAGED URBAN WATERSHEDS By V. A. Stricker and V. B. Sauer (I've attached below), see pg 2 - 6, Estimating Design Flood Hydrographs, which report was referenced in NSS documentation under Flood hydrograph Estimation
>The procedure used in NSS to compute the average hydrograph is known as the dimensionless-hydrograph method. Stricker and Sauer (1982) developed the method for urban basins using theoretical techniques.

I've also included a snapshot of an spreadsheet that I just used to check the ID Peak regoin 3 with Drainage area 700 sqr miles and mean Elevation = 4000 ft
which match the output of the online application.
* If this is not correct method, please let us know and we will address.

[TechEstimatingFloodHydr1982.pdf](https://github.com/USGS-WiM/NSS/files/817715/TechEstimatingFloodHydr1982.pdf)
![image](https://cloud.githubusercontent.com/assets/8713714/23566549/92bb1798-000f-11e7-9e02-5dec0b67fed6.png)

**Comment by jknewson** [comment]
Just talked it over w/ Todd.. It looks like I grabbed the wrong report to base our method off of. Below is the correct report.
https://pubs.usgs.gov/wsp/2317/report.pdf

**Comment by HansVraga** [comment]
Updated the title to reflect what this issue has evolved into.

**Comment by jknewson** [comment]
Here is the new table extracted from https://pubs.usgs.gov/wsp/2317/report.pdf
[SimulationofFloodHydrographs.pdf](https://github.com/USGS-WiM/NSS/files/1102511/SimulationofFloodHydrographs.pdf)
![image](https://user-images.githubusercontent.com/8713714/27545982-9015aaa0-5a4e-11e7-9e26-0f05ffafd9c6.png)

**Comment by troddick** [comment]
done
