### ISSUE TITLE
Add in DA_Exponent and OrderIndex for Equations

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#450]
- [x] User should be able to set these when creating an equation
- [x] Display in equation edit screen
- [x] Make sure these are included in the batch upload modal as well

- We'll also be adding the DARatio range min and max in once they are ready in the services

**Comment by harper-wavra** [comment]
Where to display new data columns:

The equivalent years of record is a type of error reporting that could be added to errors. The drainage area exponent is  really part of an equation for a different method and could be listed under the equation heading. And finally, the order level might be resolved with database sorting but if not, then could be grouped with the column for name as it is how we want to sort or order the equations (typically by name).
