### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#461]
I thought we had this - but looks like we don't! We'll want to add the google tag info below to the index.html, and figure out what is important to document. 

We can ask Pete what he might want to see, but initial thoughts are to track when equations are computed, when scenarios are added, edited or deleted, and any other basic function. We can include the region/state and statistic groups in case Pete wants to see the frequency of those things (or maybe say "all" if no filters are applied).

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-2C1QXBBXVH"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-2C1QXBBXVH');
</script>
```

**Comment by harper-wavra** [comment]
Is there a log in for this, or a way to test if it is working?

**Comment by kjacobsen16** [comment]
@harper-wavra we added your email to the WIM Analytics account (thanks to Lauren). You should be able to view "NSS (StreamStats)" (ignore the "NSS (StreamStats) - GA4" one).

If you'd like to do a call for a quick rundown of Google Analytics let me know!
