### ISSUE TITLE
Add WMA Analytics

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#467]
>If a WMA application, add to the WMA Internal Analytics page: https://github.com/USGS-VIZLAB/internal-analytics (see ReadMe) 

>(You can just make a pull request with changes to this yaml file: https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/gaTable.yaml#L779 with whatever new IDs and views the dashboard should use for those applications.)

**Comment by harper-wavra** [comment]
I looked at other WIM application in the yaml file and was able to figure out some fields however I am not sure what to use for viewID, webPropertyId, internalWebPropertyId, viewName, or timeZone.

Maybe we need to email David Watkins (from the readme) for more instructions?

 ```
longName: "National Streamflow Statistics"
shortName: "NSS"
accountName: "WIM USGS"
viewID: ?
accountId: '61219868'
webPropertyId: ?
internalWebPropertyId: ?
viewName: ?
timezone: ?
websiteUrl: https://streamstats.usgs.gov/nss/
botFilteringEnabled: 'NA'
description: >-
    An Angular CLI web application, the National Streamflow Statistics (NSS) Program is a computer program that provides a 
   simple method for applying regional flood-peak streamflow estimates and low flow frequency/duration streamflow estimates  projectContact: 'Hans Vraga'
projectContactEmail: 'hvraga@usgs.gov'
analyticsContact: 'Hans Vraga'
analyticsContactEmail: 'hvraga@usgs.gov'
```

**Comment by kjacobsen16** [comment]
@harper-wavra 
viewID: 244586757
webPropertyId: UA-61219868-49 (got this from the GA account)
viewName: All Web Site Data
timezone: America/New_York

I was able to find most of those in the Google Analytics page. That leaves the internalWebPropertyId, which I notice some of them don't have. You can mention that in your pull request, that you didn't include that ID but see that some have it and ask what it's for.

While you're in there, can you update the StreamStats url to "https://streamstats.usgs.gov/ss/"?

Also, I would change the description (pulled this from our About window):
>The National Streamflow Statistics (NSS) program provides the U.S. Geological Survey developed and published regression equations, such as mean annual and monthly mean flows, flow-duration percentiles, and peak and low flows for or every State, the Commonwealth of Puerto Rico, and several metropolitan areas in the United States. The program is used for a variety of water-resource purposes, such as bridge and culvert design, and emergency planning and management such as drought and flood zone identification and total maximum daily load estimates in ungaged locations.

**Comment by harper-wavra** [comment]
Created pull request: https://github.com/USGS-VIZLAB/internal-analytics/pull/250

**Comment by harper-wavra** [comment]
New pull request: https://github.com/usgs-makerspace/analytics_pipeline/pull/65
