### ISSUE TITLE
Configure for USA Analytics

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#468]
@lprivette help

**Comment by lprivette** [comment]
Emailed DAP with request on 6/30

**Comment by lprivette** [comment]
> After the code is implemented and is sending data to DAP Google Analytics, you can submit your list of users to be granted access. Showing up on analytics.usa.gov depends on how much volume your site receives, and whether it has enough to appear in the top sites. It doesn't depend on user access. Please respond here notifying us when you've implemented so we can QA. 

So once it's deployed, we can request user accounts to access the ga data. I don't actually have one of these accounts so I don't know what it looks like. But let me know once it's deployed and I'll let Freddie at DAP know so they can QA

**Comment by kjacobsen16** [comment]
Thanks @lprivette! Should I alert you when it's deployed to staging, or just production?

**Comment by kjacobsen16** [comment]
@lprivette we've pushed it up to the production site (https://streamstats.usgs.gov/nss/).

**Comment by lprivette** [comment]
I'm sorry I missed your previous comment, but yes needed to know when it's in prod (they'll go in and inspect the added js tag). Emailing now and will follow up with their repsonse

**Comment by kjacobsen16** [comment]
Thanks!

**Comment by lprivette** [comment]
> Thanks for your note. I see DAP firing on your initial homepage page load, but not on any other pages. If the DAP code doesn't fire on page load on every page, you won't have any data. Can you confirm the codebase used, and if your development team implemented DAP on every page?
> 
> If you're using any type of single page app framework or something like react.js or vue.js, you'll need to implement virtual pageviews. 

Are there other pages? Briefly looking at it and not actually understand this app, it doesn't look like it.

Should I ask about the virtual pageviews? I'd bet that angular would fall under similar requirements to vue or react.

For our other apps we've used this analytics in it's just been put in the index. I think all of those apps are jquery/arcgis for js.

**Comment by kjacobsen16** [comment]
There's just the one page for now, but there are additional pages in the codebase that are disabled in this release, which is what he might be seeing.

But yeah, let's ask him about the virtual pageviews, but I don't know if we'll need it since users are just on this page...

**Comment by lprivette** [comment]
how soon before those other pages are enabled? Wonder if it's worth putting the code in those ones now.

**Comment by kjacobsen16** [comment]
Sure, *I'm guessing a few months or so but it all depends on other priorities.

So yeah we should probably add it in now!

**Comment by lprivette** [comment]
The DAP rep is amazingly unhelpful. He provided no clarification about the 'virtual page views' when directly asked for it. 

As I understand it, analytics.gov will register a user when the homepage loads the first time, which is I believe what we want.

He states "Any other pages that your audience visits after their initial entry into the site, will not fire the DAP script". Despite having told him we have the one page right now https://streamstats.usgs.gov/nss/. He used a dropdown as an example for virtual page view usage, which doesn't make sense to me and you all are using events anyways so 👎 

just posting this here so it's a least recorded somewhere. I'll attempt to get a confirmation that we are setup for the 'limited' analytics collection

**Comment by kjacobsen16** [comment]
Thanks @lprivette! Consider this issue closed!
