### ISSUE TITLE
Add NSS Production app to Uptime bot

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#469]
(when we push to production)
https://github.com/USGS-WiM/wim-infrastructure/wiki/Monitoring-with-Uptimebot-and-FGDC-status-checker

**Comment by kjacobsen16** [comment]
@harper-wavra can you look into this now that we've released NSS?

**Comment by harper-wavra** [comment]
Yes I can., however I do not have access to the link in the description.

**Comment by kjacobsen16** [comment]
Oh right, we haven't done full onboarding. I'll see if we can get you added!

**Comment by kjacobsen16** [comment]
Actually, we'll need Hans to do that since our github org is full (there's a limitation on full group members). I'll go ahead and do this issue for now, and we'll work on getting you set up with everything soon.

**Comment by kjacobsen16** [comment]
Added, contacts may need adjusting at some point
