### ISSUE TITLE
Check Frequency Plot

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#476]
My guess is the plot tries to read the "PK50" instead of "PK50AEP", etc.

![image](https://user-images.githubusercontent.com/35497731/124021162-d7a02400-d9b0-11eb-92c8-87c7342e4d5b.png)

**Comment by harper-wavra** [comment]
I took a look at this morning at this, but I might need some more explanation about what is it suppose to be plotting. I can see the value is the y axis but what should it be grabbing for the x, or the Recurrence Interval, in years?

![image](https://user-images.githubusercontent.com/59063181/124145147-29e55180-da52-11eb-9bc9-07ab3a65ba9b.png)

**Comment by kjacobsen16** [comment]
@harper-wavra the stat labels used to be "20 year peak flood", etc. instead of the current % annual exceedance probability stat labels. We should double check to see what the code is doing. I'm guessing it's parsing out the number by stripping out " Year Peak Flood" and just taking the number in front, which of course would break if the stat labels changed.

Since the stat labels have all been changed to the % annual exceedance probabilities, we'll just need to change how we're parsing the stat labels and convert it back to the proper value. So, you'd parse out the percent from the name (you can use a regex to get all numeric values including decimals before the % sign) and convert it by dividing 100 by the % AEP, so:
50% AEP = 100 / 50 = 2 year peak flood (so 2 would be the x value)
1% AEP = 100 / 1 = 100
0.2% AEP = 100 / 0.2 = 500

**Comment by harper-wavra** [comment]
@USGSPMM3 While doing the go-live checklist this week we noticed that the frequency plot was broken from changing the stat labels. I am working on getting the plots working again and had a question. It used to be chart `type = line` but it looked a little weird to me so I changed it to `type = scatter` just to see what that would look like. I am just wondering which you prefer? 

I included a screenshot of each with 8 statistics from California.
[line chart](https://user-images.githubusercontent.com/59063181/124285447-8a889300-db13-11eb-954a-c64f2fcca07a.png)
[scatter chart](https://user-images.githubusercontent.com/59063181/124285492-9411fb00-db13-11eb-83e6-443703fe4578.png)

**Comment by kjacobsen16** [comment]
@USGSPMM3 to clarify, this was from changing the "x year peak flood" to the %AEP stat labels

**Comment by USGSPMM3** [comment]
@harper-wavra and @kjacobsen16 
Several comments:
1. We should include lines so users can interpret between points.
2. When plotting the flood frequency plots, a group of points for a region should make one plot, a group of points from another region would make another plot. A key would be needed to differentiate the results for each region, such that region a values have a dashed line, region be values have a solid line etc. OR
3. Make the users select a region to plot and only allow one region per plot. This would simplify the plots
4. We should be plotting confidence intervals too. I'm not sure if this was part of the original functionality.

**Comment by harper-wavra** [comment]
@USGSPMM3 So we want it to look more like this?
![image](https://user-images.githubusercontent.com/59063181/124657012-8d62eb00-de67-11eb-8c69-97e12c8ba0dd.png)
