### ISSUE TITLE
Get ORC IDs for Andrea and Harper, add to IPDS

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#479]

**Comment by kjacobsen16** [comment]
@harper-wavra attach your ORC ID here when you have one

**Comment by harper-wavra** [comment]
0000-0001-5688-902X

**Comment by kjacobsen16** [comment]
@harper-wavra can you double check that? I don't think they usually have letters, and I can't find this in the ORCID lookup

**Comment by harper-wavra** [comment]
Can you get to this link? Its working for me: https://orcid.org/0000-0001-5688-902X

**Comment by kjacobsen16** [comment]
Harper added as an author in IPDS

After further discussion with Andrea, we are not adding her as an author to this initial release
