### ISSUE TITLE
Help Form submission to Freshdesk broke

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSS#511]
Appears (in prod: https://streamstats.usgs.gov/nss/ ) that submission of a help request is broken:

![image](https://user-images.githubusercontent.com/12058013/132031789-0d54c357-9c7f-47ed-b5d3-a78a02de07ab.png)

**Comment by harper-wavra** [comment]
~~I am thinking that the secrets.json didn't get added to the dist folder when we put it on PROD. Will have to check how SS handles it.~~

I was correct, we need to add it to the assets folder in AWS (thats how SS is working). Not sure how to get it to not show up in the network tools though.

**Comment by harper-wavra** [comment]
Added file back and tested, seems to be working now.
