### ISSUE TITLE
MathJax Errors

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSS#530]
DOI has started blocking different scripts needed for different librarys. We are using MathJax and when users are on network (in office or on VPN), the script needed to make mathjax worked is blocked.

We might need to upgrade the package or reach out to the USGS Servicedesk.

![image](https://user-images.githubusercontent.com/59063181/160889583-65c51436-bc09-451f-a99b-633722a0eadb.png)

**Comment by harper-wavra** [comment]
Cause: Cloudflare has been blocked on network, so dependencies loading like so https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=AM_HTMLorMML-full will fail.

Need to find an alternate source

**Comment by harper-wavra** [comment]
Some instructions: https://docs.mathjax.org/en/v2.7-latest/start.html
Can maybe just use raw github file: https://raw.githubusercontent.com/mathjax/MathJax/2.7.9/MathJax.js

**Comment by amedenblik** [comment]
Note: Cloudfare appears to no longer be blocked on the DOI network
