### ISSUE TITLE
Add "About" Modal

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSS#58]
Add an About Modal so we can add the standard USGS disclaimer, Contact information for NSS.

**Comment by troddick** [comment]
Need content to add

**Comment by HansVraga** [comment]
- [x] Heading - National Streamflow Statistics client application version X.X

- [x] About Tab:
About National Streamflow Statistics (NSS) client application. 
Spicy jalapeno bacon ipsum dolor amet ea short loin non, exercitation kielbasa brisket mollit alcatra rump swine boudin tempor ribeye ipsum. In velit in strip steak pork beef ribs. Pariatur doner spare ribs, anim velit fugiat consectetur ipsum cillum short loin tenderloin adipisicing. Leberkas kielbasa eu tri-tip consequat, ad laboris jowl short loin ea bacon ham hock. Turkey deserunt non tenderloin alcatra jerky pork loin shoulder fatback reprehenderit aute minim shank. Shank burgdoggen magna flank, qui aliqua porchetta laborum ribeye turducken pastrami labore eiusmod.
Ham hock proident brisket, quis cow sausage capicola lorem ut flank. Commodo cillum et swine sed anim duis officia ullamco pariatur. Ex beef ribs eiusmod ground round exercitation ham hock duis meatball strip steak pork chop dolor filet mignon short loin. Excepteur sint pastrami duis, sunt hamburger occaecat short ribs prosciutto. Ad meatloaf shoulder aliquip pork chop swine porchetta alcatra.

- [x] Disclaimer Tab
This software is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely best science. The software has not received final approval by the U.S. Geological Survey (USGS). No warranty, expressed or implied, is made by the USGS or the U.S. Government as to the functionality of the software and related material nor shall the fact of release constitute any such warranty. The software is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the software.

**Comment by troddick** [comment]
Added. Even figured out how to tap into the package.json file and grab the  version number to show in the about modal. :)
I will close this for now and when we have more content to add/replace in this modal, it can be reopened.
