### ISSUE TITLE
Add "Powered by WiM" and other footer links in sidebar

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSS#59]
- [x] Powered by WiM (as link to WiM Website, like StreamStats)

- [x] USGS standard Footer links

**Comment by troddick** [comment]
example of where to find usgs standard footer links please. Put these in the sidebar footer or across the whole bottom?

**Comment by HansVraga** [comment]
![image](https://user-images.githubusercontent.com/12058013/31090417-8e2bb422-a775-11e7-902d-144dccf4abbd.png)

**Comment by HansVraga** [comment]
StreamStats Example.
![image](https://user-images.githubusercontent.com/12058013/31090441-9be840ee-a775-11e7-8e79-de53ea32a14e.png)

**Comment by troddick** [comment]
done
