### ISSUE TITLE
Change the displayed region code instead of ID.

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSS#69]
Displaying ID's aren't really useful outside the db, code is probably the better identifier to use.
![image](https://user-images.githubusercontent.com/8713714/38205810-209828da-3665-11e8-8507-b3b6d8d5063a.png)

**Comment by HansVraga** [comment]
yeah.
![image](https://user-images.githubusercontent.com/12058013/45779036-46a09980-bc17-11e8-8ea0-6ed11d23672a.png)

**Comment by kjacobsen16** [comment]
done
