### ISSUE TITLE
Part of Todd's review - Issue 1, weird rounding for AK D15 

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSS#71]
![image](https://user-images.githubusercontent.com/8713714/49737740-d5d3b100-fc4a-11e8-8622-9f3f2367eb6c.png)
Should be 11,800,000
The value coming from nssservices is 11812235.2250751

Other equations tend to round correctly.

**Comment by harper-wavra** [comment]
Closer still too many significant figures.
Alaska has different rounding rules.

![image](https://user-images.githubusercontent.com/59063181/75362035-c8214000-587d-11ea-91d1-2294ee410857.png)
