### ISSUE TITLE
Dealing with short name underscores in MathJax

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSS#72]
The equation render seems to be slow when rendering the equations, I think they are kinda fun. But any parameter that has an underscore in the short name loses it's underscore and causes the next letter after the underscore to render as a subscript. You may already be aware of it and have no recourse

**Comment by harper-wavra** [comment]
Two options to consider:
-considering removing all shortname underscores
-adding help text to NSS describing how to tell mathjax "escape" the underscore character & accounting for that in client

**Comment by HansVraga** [comment]
After discussion, we'll pursue fixing this in the client with a combination of help text and handling the underscore display (no removing underscores in shortnames)
