### ISSUE TITLE
Part of Todds review - Need a way to quickly reset all state filters

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSS#73]
really just about having a fast method of resetting all the filters except for State (staying on the the same State but resetting the Statistic Group, Regression Group, and Statistic filters).  The long way is to click each of those three filters and select "Uncheck All" (6 clicks total).  Or, it takes fewer clicks but is less obvious to refresh the page and re-select the State (3 clicks).  Or, a person may eventually learn to just select a different State, then re-select the State they were on (4 clicks).

**Comment by kjacobsen16** [comment]
This was finished a while ago
