### ISSUE TITLE
Add way to associate regions to a manager

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#75]
Associated with https://github.com/USGS-WiM/NSSServices/issues/93, once service endpoint is added, add multiselect dropdown when adding/editing regions to add managers to that region

**Comment by kjacobsen16** [comment]
This service endpoint is ready. The managers object contains a `regionManagers` object, see the TestManager manager. You can add more by replicating that object and sending it through with the edits. You'll need to add the `regionManagers` object to the form and to the manager interface.

**Comment by amedenblik** [comment]
This might be needed for gagestats if managers are set up in the same way

**Comment by kjacobsen16** [comment]
Note on this - currently the services don't allow editing of regions associated to managers, so we'll only want it available when _creating_ a manager, and to show up as an un-editable column in the table.
