### ISSUE TITLE
In About

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSS#86]
From Kernell review:
- [x] change the link to the new NSS home page to that it automatically opens in a new tab.
- [x] add as a second paragraph, “Much of the functionality in the NSS program is also available in the StreamStats application (https://streamstats.usgs.gov). StreamStats provides a map-based user interface that allows selection of of interest and automates the process of computing basin characteristics and estimating flow statistics for ungaged sites. StreamStats also provide access to previously computed information for gaged sites. As a result, StreamStats normally should be used in areas where it is available. However, NSS has the additional capabilities of providing: (1) peak-flow frequency plots, (2) peak-flow hydrograph plots, (3) maximum flood estimates based on envelope curves developed by Crippen and Bue (1977), (4) peak-flow estimates for gaged sites determined by weighting estimates from the systematic record with those from the relevant regression equations, and (5) peak-flow estimates for ungaged sites that are determined by weighting regression-based estimates for the sites with weighted estimates for a nearby gaged site.  

- [ ] The NSS web page, https://www.usgs.gov/software/national-streamflow-statistics-program-nss, will need to be updated to correspond with the new web-based version of the program, when it is ready for release. I suggest including a similar paragraph as that above in the new version of the NSS page.

**Comment by harper-wavra** [comment]
Created issue #125 to address last item, closing this issue.
