### ISSUE TITLE
Add Manage Citations button near edit scenario button

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSS#89]
with https://github.com/USGS-WiM/NSSServices/issues/97

>Maybe the easiest/ straight forward way of handing this is adding another button next to add/edit scenario,  something like manage citations, which shows a modal of all citations (filtered when logged in etc) that shows the citation and which regression region they are associated to (I don't think that endpoint exists yet, but should be easy to set up). The delete button can be disabled if there is an association to any type of reg region. That way the user can easily see that they need to go to that reg-region and remove the citation before they can delete it

**Comment by kjacobsen16** [comment]
@harper-wavra @amedenblik this doesn't have a service endpoint yet to see which regression region the citations are associated to, but setting up the button and modal, and maybe just pulling all citations for now is a good place to start

**Comment by amedenblik** [comment]
I'm going to try to tackle this issue.

**Comment by kjacobsen16** [comment]
Manage citations modal added - will need more work once services are set up

**Comment by kjacobsen16** [comment]
@amedenblik the endpoint is now live! You can see/test it in the documentation here: https://test.streamstats.usgs.gov/docs/nssservicesv2/#/RegressionRegions/GET/RegressionRegions.

You call it exactly the same as the regular regression regions calls, but with the "bycitations" parameter sent through as true.

I don't think you've set up a service call yet for this app. You can start by looking at the regressionregions call when a user selects a region. Let me know if you need help, and I'll point you in the right direction :)

**Comment by kjacobsen16** [comment]
Making a note here because I almost forgot.. This is waiting for the Angular update (#100) since the http requests will be different

**Comment by amedenblik** [comment]
Removing myself from this issue since I am running low on hours. Harper and KJ, please let me know if you have questions.

**Comment by kjacobsen16** [comment]
@harper-wavra I added the regression regions to the get all citations endpoint, so you should be able to loop through those now and add them to the modal. I'll take a look at your latest commits soon.
